---
name: Build site
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '5 4 * 9,10 0'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git checkout -b gh-pages
      - run: pip3 install -r requirements.txt
      - run: python3 generate_json.py
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
      - run: python3 generate_site_from_json.py
      - run: 'echo "droidtoberfest.sylviavanos.nl" > docs/CNAME'
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git add --force docs
      - run: git commit -m "Build website"
      - run: git push --force -u origin gh-pages
